In [ ]:
%pip install geopandas shapely pyproj rasterio contextily folium scikit-learn jupyterlab xgboost

Requirement already satisfied: geopandas in ./venv/lib/python3.11/site-packages (1.0.1)
Requirement already satisfied: shapely in ./venv/lib/python3.11/site-packages (2.1.0)
Requirement already satisfied: pyproj in ./venv/lib/python3.11/site-packages (3.7.1)
Requirement already satisfied: rasterio in ./venv/lib/python3.11/site-packages (1.4.3)
Requirement already satisfied: contextily in ./venv/lib/python3.11/site-packages (1.6.2)
Requirement already satisfied: folium in ./venv/lib/python3.11/site-packages (0.19.6)
Requirement already satisfied: scikit-learn in ./venv/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: jupyterlab in ./venv/lib/python3.11/site-packages (4.4.2)
Requirement already satisfied: numpy>=1.22 in ./venv/lib/python3.11/site-packages (from geopandas) (2.2.5)
Requirement already satisfied: pyogrio>=0.7.2 in ./venv/lib/python3.11/site-packages (from geopandas) (0.11.0)
Requirement already satisfied: packaging in ./venv/lib/python3.11/site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=1.4.0 in ./venv/lib/python3.11/site-packages (from geopandas) (2.2.3)
Requirement already satisfied: certifi in ./venv/lib/python3.11/site-packages (from pyproj) (2025.4.26)
Requirement already satisfied: affine in ./venv/lib/python3.11/site-packages (from rasterio) (2.4.0)
Requirement already satisfied: attrs in ./venv/lib/python3.11/site-packages (from rasterio) (25.3.0)
Requirement already satisfied: click>=4.0 in ./venv/lib/python3.11/site-packages (from rasterio) (8.2.0)
Requirement already satisfied: cligj>=0.5 in ./venv/lib/python3.11/site-packages (from rasterio) (0.7.2)
Requirement already satisfied: click-plugins in ./venv/lib/python3.11/site-packages (from rasterio) (1.1.1)
Requirement already satisfied: pyparsing in ./venv/lib/python3.11/site-packages (from rasterio) (3.2.3)
Requirement already satisfied: geopy in ./venv/lib/python3.11/site-packages (from contextily) (2.4.1)
Requirement already satisfied: matplotlib in ./venv/lib/python3.11/site-packages (from contextily) (3.10.3)
Requirement already satisfied: mercantile in ./venv/lib/python3.11/site-packages (from contextily) (1.2.1)
Requirement already satisfied: pillow in ./venv/lib/python3.11/site-packages (from contextily) (11.2.1)
Requirement already satisfied: requests in ./venv/lib/python3.11/site-packages (from contextily) (2.32.3)
Requirement already satisfied: joblib in ./venv/lib/python3.11/site-packages (from contextily) (1.5.0)
Requirement already satisfied: xyzservices in ./venv/lib/python3.11/site-packages (from contextily) (2025.4.0)
Requirement already satisfied: branca>=0.6.0 in ./venv/lib/python3.11/site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in ./venv/lib/python3.11/site-packages (from folium) (3.1.6)
Requirement already satisfied: scipy>=1.6.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: async-lru>=1.0.0 in ./venv/lib/python3.11/site-packages (from jupyterlab) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in ./venv/lib/python3.11/site-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: ipykernel>=6.5.0 in ./venv/lib/python3.11/site-packages (from jupyterlab) (6.29.5)
Requirement already satisfied: jupyter-core in ./venv/lib/python3.11/site-packages (from jupyterlab) (5.7.2)
Requirement already satisfied: jupyter-lsp>=2.0.0 in ./venv/lib/python3.11/site-packages (from jupyterlab) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in ./venv/lib/python3.11/site-packages (from jupyterlab) (2.16.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in ./venv/lib/python3.11/site-packages (from jupyterlab) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in ./venv/lib/python3.11/site-packages (from jupyterlab) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in ./venv/lib/python3.11/site-packages (from jupyterlab) (65.5.0)
Requirement already satisfied: tornado>=6.2.0 in ./venv/lib/python3.11/site-packages (from jupyterlab) (6.5)
Requirement already satisfied: traitlets in ./venv/lib/python3.11/site-packages (from jupyterlab) (5.14.3)
Requirement already satisfied: anyio in ./venv/lib/python3.11/site-packages (from httpx>=0.25.0->jupyterlab) (4.9.0)
Requirement already satisfied: httpcore==1.* in ./venv/lib/python3.11/site-packages (from httpx>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: idna in ./venv/lib/python3.11/site-packages (from httpx>=0.25.0->jupyterlab) (3.10)
Requirement already satisfied: h11>=0.16 in ./venv/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: appnope in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (0.1.4)
Requirement already satisfied: comm>=0.1.1 in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (1.8.14)
Requirement already satisfied: ipython>=7.23.1 in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (9.2.0)
Requirement already satisfied: jupyter-client>=6.1.12 in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (8.6.3)
Requirement already satisfied: matplotlib-inline>=0.1 in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (0.1.7)
Requirement already satisfied: nest-asyncio in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (1.6.0)
Requirement already satisfied: psutil in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (7.0.0)
Requirement already satisfied: pyzmq>=24 in ./venv/lib/python3.11/site-packages (from ipykernel>=6.5.0->jupyterlab) (26.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: platformdirs>=2.5 in ./venv/lib/python3.11/site-packages (from jupyter-core->jupyterlab) (4.3.8)
Requirement already satisfied: argon2-cffi>=21.1 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (23.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.16.6)
Requirement already satisfied: nbformat>=5.3.0 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (5.10.4)
Requirement already satisfied: overrides>=5.0 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.22.0)
Requirement already satisfied: send2trash>=1.8.2 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in ./venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.8.0)
Requirement already satisfied: babel>=2.10 in ./venv/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in ./venv/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (0.12.0)
Requirement already satisfied: jsonschema>=4.18.0 in ./venv/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (4.23.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.11/site-packages (from requests->contextily) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.11/site-packages (from requests->contextily) (2.4.0)
Requirement already satisfied: geographiclib<3,>=1.52 in ./venv/lib/python3.11/site-packages (from geopy->contextily) (2.0)
Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.11/site-packages (from matplotlib->contextily) (1.3.2)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.11/site-packages (from matplotlib->contextily) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.11/site-packages (from matplotlib->contextily) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./venv/lib/python3.11/site-packages (from matplotlib->contextily) (1.4.8)
Requirement already satisfied: sniffio>=1.1 in ./venv/lib/python3.11/site-packages (from anyio->httpx>=0.25.0->jupyterlab) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in ./venv/lib/python3.11/site-packages (from anyio->httpx>=0.25.0->jupyterlab) (4.13.2)
Requirement already satisfied: argon2-cffi-bindings in ./venv/lib/python3.11/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (21.2.0)
Requirement already satisfied: decorator in ./venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in ./venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (1.1.1)
Requirement already satisfied: jedi>=0.16 in ./venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.19.2)
Requirement already satisfied: pexpect>4.3 in ./venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in ./venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in ./venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (2.19.1)
Requirement already satisfied: stack_data in ./venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.6.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in ./venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in ./venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (0.25.0)
Requirement already satisfied: python-json-logger>=2.0.4 in ./venv/lib/python3.11/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in ./venv/lib/python3.11/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (6.0.2)
Requirement already satisfied: rfc3339-validator in ./venv/lib/python3.11/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in ./venv/lib/python3.11/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.1)
Requirement already satisfied: beautifulsoup4 in ./venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.13.4)
Requirement already satisfied: bleach[css]!=5.0.0 in ./venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (6.2.0)
Requirement already satisfied: defusedxml in ./venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in ./venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in ./venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in ./venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in ./venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in ./venv/lib/python3.11/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab) (2.21.1)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.17.0)
Requirement already satisfied: ptyprocess in ./venv/lib/python3.11/site-packages (from terminado>=0.8.3->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.0)
Requirement already satisfied: webencodings in ./venv/lib/python3.11/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in ./venv/lib/python3.11/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.4.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in ./venv/lib/python3.11/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.8.4)
Requirement already satisfied: fqdn in ./venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.5.1)
Requirement already satisfied: isoduration in ./venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in ./venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (3.0.0)
Requirement already satisfied: uri-template in ./venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in ./venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (24.11.1)
Requirement already satisfied: wcwidth in ./venv/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.2.13)
Requirement already satisfied: cffi>=1.0.1 in ./venv/lib/python3.11/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in ./venv/lib/python3.11/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (2.7)
Requirement already satisfied: executing>=1.2.0 in ./venv/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in ./venv/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (3.0.0)
Requirement already satisfied: pure-eval in ./venv/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.2.3)
Requirement already satisfied: pycparser in ./venv/lib/python3.11/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (2.22)
Requirement already satisfied: arrow>=0.15.0 in ./venv/lib/python3.11/site-packages (from isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in ./venv/lib/python3.11/site-packages (from arrow>=0.15.0->isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (2.9.0.20250516)

[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [53]:
%pip list

Package                   Version
------------------------- --------------
affine                    2.4.0
anyio                     4.9.0
appnope                   0.1.4
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.4
bleach                    6.2.0
branca                    0.8.1
certifi                   2025.4.26
cffi                      1.17.1
charset-normalizer        3.4.2
click                     8.2.0
click-plugins             1.1.1
cligj                     0.7.2
comm                      0.2.2
contextily                1.6.2
contourpy                 1.3.2
cycler                    0.12.1
debugpy                   1.8.14
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.0
fastjsonschema            2.21.1
folium                    0.19.6
fonttools                 4.58.0
fqdn                      1.5.1
geographiclib             2.0
geopandas                 1.0.1
geopy                     2.4.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.10
ipykernel                 6.29.5
ipython                   9.2.0
ipython_pygments_lexers   1.1.1
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
joblib                    1.5.0
json5                     0.12.0
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2025.4.1
jupyter_client            8.6.3
jupyter_core              5.7.2
jupyter-events            0.12.0
jupyter-lsp               2.2.5
jupyter_server            2.16.0
jupyter_server_terminals  0.5.3
jupyterlab                4.4.2
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
kiwisolver                1.4.8
MarkupSafe                3.0.2
matplotlib                3.10.3
matplotlib-inline         0.1.7
mercantile                1.2.1
mistune                   3.1.3
nbclient                  0.10.2
nbconvert                 7.16.6
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.4.2
notebook_shim             0.2.4
numpy                     2.2.5
overrides                 7.7.0
packaging                 25.0
pandas                    2.2.3
pandocfilters             1.5.1
parso                     0.8.4
pexpect                   4.9.0
pillow                    11.2.1
pip                       23.1.2
platformdirs              4.3.8
prometheus_client         0.22.0
prompt_toolkit            3.0.51
psutil                    7.0.0
ptyprocess                0.7.0
pure_eval                 0.2.3
pycparser                 2.22
Pygments                  2.19.1
pyogrio                   0.11.0
pyparsing                 3.2.3
pyproj                    3.7.1
python-dateutil           2.9.0.post0
python-json-logger        3.3.0
pytz                      2025.2
PyYAML                    6.0.2
pyzmq                     26.4.0
rasterio                  1.4.3
referencing               0.36.2
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.25.0
scikit-learn              1.6.1
scipy                     1.15.3
Send2Trash                1.8.3
setuptools                65.5.0
shapely                   2.1.0
six                       1.17.0
sniffio                   1.3.1
soupsieve                 2.7
stack-data                0.6.3
terminado                 0.18.1
threadpoolctl             3.6.0
tinycss2                  1.4.0
tornado                   6.5
traitlets                 5.14.3
types-python-dateutil     2.9.0.20250516
typing_extensions         4.13.2
tzdata                    2025.2
uri-template              1.3.0
urllib3                   2.4.0
wcwidth                   0.2.13
webcolors                 24.11.1
webencodings              0.5.1
websocket-client          1.8.0
xgboost                   3.0.1
xyzservices               2025.4.0

[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# import requests

# url    = "https://phl.carto.com/api/v2/sql"
# params = {
#     "q": """
#       SELECT
#         *,
#         ST_AsGeoJSON(the_geom)::json AS geometry
#       FROM assessments
#       WHERE year > 2022
#     """,
#     "format": "GeoJSON"
# }

# resp = requests.get(url, params=params)
# resp.raise_for_status()

# with open("data/opa_properties_public.geojson", "w") as f:
#     f.write(resp.text)

import requests

url    = "https://phl.carto.com/api/v2/sql"
params = {
    "q": """
      SELECT
        *,
        ST_AsGeoJSON(the_geom)::json AS geometry
      FROM opa_properties_public
      WHERE assessment_date >= '2022-01-01'
    """,
    "format": "GeoJSON"
}

resp = requests.get(url, params=params)
resp.raise_for_status()

props = resp.json()
print(f"Retrieved {len(resp['features'])} features.")
with open("data/opa_properties_public.geojson", "w") as f:
    f.write(props.text)

In [ ]:
import requests

# Endpoint and parameters
url = "https://phl.carto.com/api/v2/sql"
params = {
    "q": "SELECT *, ST_AsGeoJSON(the_geom)::json AS the_geom_geojson FROM public_cases_fc WHERE requested_datetime >= '2022-01-01'",
    "format": "GeoJSON"
}

# Send the GET request
resp = requests.get(url, params=params)
resp.raise_for_status()  # will raise if response code is 4xx/5xx

# Parse as GeoJSON
calls = resp.json()
print(f"Retrieved {len(calls['features'])} features.")
with open("data/311.geojson", "w") as f:
    f.write(resp.text)

Retrieved 1831001 features.

In [8]:
import geopandas as gpd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import folium
import numpy as np

In [9]:
# 1. Load property polygons

props = gpd.read_file("data/opa_properties_public.geojson").to_crs(3857)

# 2. Load 311 point data and spatial‑join to parcels

calls = gpd.read_file("data/311.geojson").to_crs(3857)

joined = gpd.sjoin(props, calls[['geometry','service_name']], how="left")

In [10]:
props

,cartodb_id,assessment_date,basements,beginning_point,book_and_page,building_code,building_code_description,category_code,category_code_description,census_tract,...,view_type,year_built,year_built_estimate,zip_code,zoning,pin,building_code_new,building_code_description_new,objectid,geometry
0,1,2024-06-06 00:00:00+00:00,H,"65'5"" W OF 18TH ST",54421066,R50,ROW B/GAR 3 STY MASONRY,1,SINGLE FAMILY,373,...,I,1960,Y,19145,RSA5,1001474749,21,ROW OLD STYLE,625493651,POINT (-8368801.614 4853114.259)
1,2,2024-06-06 00:00:00+00:00,A,117' W OF 18TH ST,54421184,O50,ROW 3 STY MASONRY,1,SINGLE FAMILY,140,...,I,1915,Y,19121,RSA5,1001520353,22,ROW TYPICAL,625493652,POINT (-8367444.407 4862158.067)
2,3,2024-06-06 00:00:00+00:00,D,"135'11 1/2""N MIFFLIN",54421270,O10,ROW 1 STY MASONRY,1,SINGLE FAMILY,36,...,I,1950,Y,19145,RM1,1001646206,23,ROW POST WAR,625493653,POINT (-8370301.088 4855801.554)
3,4,2024-06-06 00:00:00+00:00,D,"26'5 1/2""N MIFFLIN ST",54421269,O10,ROW 1 STY MASONRY,1,SINGLE FAMILY,36,...,I,1950,Y,19145,RM1,1001646217,23,ROW POST WAR,625493654,POINT (-8370308.435 4855758.874)
4,5,2024-06-06 00:00:00+00:00,None,"297'8"" W 17TH ST",54421205,CA0,APTS 5-50 UNITS MASONRY,14,APARTMENTS > 4 UNITS,140,...,None,1915,None,19130,RM4,1001242337,806,APARTMENTS - BLT AS RESID,625493655,POINT (-8367386.855 4861872.922)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582773,1416,2024-06-06 00:00:00+00:00,None,407' W 50TH ST,54413155,H30,SEMI/DET 2 STY MASONRY,1,SINGLE FAMILY,85,...,I,1925,Y,19139,RSA5,1001140443,32,TWIN CONVENTIONAL,625494965,POINT (-8373760.007 4859901.535)
582774,1417,2024-06-06 00:00:00+00:00,None,210' W 50TH ST,54413156,O30,ROW 2 STY MASONRY,1,SINGLE FAMILY,73,...,I,1925,None,19143,RM1,1001217562,24,ROW PORCH FRONT,625494966,POINT (-8373689.542 4858083.727)
582775,1418,2024-06-06 00:00:00+00:00,F,"136'6"" N. ANNSBURY ST",54413336,R30,ROW B/GAR 2 STY MASONRY,1,SINGLE FAMILY,289,...,I,1930,Y,19120,RM1,1001232070,24,ROW PORCH FRONT,625494967,POINT (-8361284.654 4868502.519)
582776,1419,2024-06-06 00:00:00+00:00,F,278' W 46 ST,54413480,K50,S/D W/B GAR 3 STY MASONRY,1,SINGLE FAMILY,79,...,I,1925,None,19143,RSA3,1001313055,36,TWIN OLD STYLE,625494968,POINT (-8372982.218 4858811.943)
582777,1420,2024-06-06 00:00:00+00:00,D,"159'7 1/8"" NE BUCKIUS",54413128,O30,ROW 2 STY MASONRY,1,SINGLE FAMILY,184,...,I,1925,Y,19137,RSA5,1001199186,22,ROW TYPICAL,625494969,POINT (-8356616.472 4865974.685)

In [11]:
calls

,cartodb_id,objectid,service_request_id,subject,status,status_notes,service_name,service_code,agency_responsible,service_notice,requested_datetime,updated_datetime,expected_datetime,closed_datetime,address,zipcode,media_url,lat,lon,geometry
0,513308,3477876,14735655,Maintenance Complaint,Closed,None,Maintenance Complaint,None,Community Life Improvement Program,90 Business Days,2022-02-14 19:45:38+00:00,2023-02-16 08:09:46+00:00,2022-07-05 04:00:00+00:00,2022-03-24 13:11:52+00:00,2925 MASTER ST,19121,https://d17aqltn7cihbm.cloudfront.net/uploads/...,39.977715,-75.183728,POINT (-8369414.317 4862704.412)
1,536719,3416151,14653360,Will the City pickup my trash on a Holiday?,Closed,Question Answered,Information Request,SR-IR01,Streets Department,None,2022-01-05 05:27:33+00:00,2022-01-05 05:27:33+00:00,NaT,2022-01-05 05:27:33+00:00,None,None,None,NaN,NaN,None
2,537325,3416152,14653361,Will the City pickup my trash on a Holiday?,Closed,Question Answered,Information Request,SR-IR01,Streets Department,None,2022-01-05 05:28:08+00:00,2022-01-05 05:28:09+00:00,NaT,2022-01-05 05:28:08+00:00,None,None,None,NaN,NaN,None
3,537388,3420018,14658595,How do I contact the Department of Revenue?,Closed,Question Answered,Information Request,SR-IR01,Revenue,None,2022-01-07 03:02:25+00:00,2022-01-07 03:02:51+00:00,NaT,2022-01-07 03:02:25+00:00,None,None,None,NaN,NaN,None
4,538966,3420146,14658765,What is the PHL City ID?,Closed,Question Answered,Information Request,SR-IR01,Managing Director's Office- MDO,None,2022-01-07 03:44:04+00:00,2022-01-07 03:44:44+00:00,NaT,2022-01-07 03:44:04+00:00,None,None,None,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1830996,2392291,5242749,17602694,Street Light Out,Open,None,Miscellaneous,SR-MI01,Philly311 Contact Center,None,2025-05-16 11:11:52+00:00,2025-05-16 11:17:01+00:00,NaT,NaT,Tacony Creek Park,19124,None,40.026808,-75.113360,POINT (-8361580.987 4869838.71)
1830997,2392292,5242750,17602695,Abandoned Vehicle | Test record Please ignore,Closed,None,Abandoned Vehicle,SR-PD01,Police Department,120 Business Days,2025-05-16 11:16:22+00:00,2025-05-16 11:21:26+00:00,2025-11-20 05:00:00+00:00,2025-05-16 11:17:58+00:00,1600 N AMERICAN ST,19130,None,39.961714,-75.173345,POINT (-8368258.487 4860380.221)
1830998,2392293,5242751,17602696,Graffiti Removal | Test record please ignore,Closed,Other,Graffiti Removal,SR-CL01,Community Life Improvement Program,7 Business Days,2025-05-16 11:21:44+00:00,2025-05-16 11:26:51+00:00,2025-05-27 04:00:00+00:00,2025-05-16 11:26:39+00:00,CALLOWHILL ST & N CHRISTOPHER COLUMBUS BLVD,19123,None,39.956832,-75.138710,POINT (-8364402.936 4859671.205)
1830999,2392294,5242752,17602697,Graffiti Removal | Test record please ignore,Closed,None,Graffiti Removal,SR-CL01,Community Life Improvement Program,7 Business Days,2025-05-16 11:25:23+00:00,2025-05-16 11:30:29+00:00,2025-05-27 04:00:00+00:00,2025-05-16 11:26:43+00:00,CHESTNUT ST & S 23RD ST,19103,None,39.952592,-75.178176,POINT (-8368796.271 4859055.468)
1831000,2392295,5242753,17602701,Street Light Out,Open,None,Miscellaneous,SR-MI01,Philly311 Contact Center,None,2025-05-16 12:34:35+00:00,2025-05-16 12:39:41+00:00,NaT,NaT,5110 Newhall St,19144,None,40.025453,-75.170567,POINT (-8367949.241 4869641.73)

In [12]:
joined

,cartodb_id,assessment_date,basements,beginning_point,book_and_page,building_code,building_code_description,category_code,category_code_description,census_tract,...,year_built_estimate,zip_code,zoning,pin,building_code_new,building_code_description_new,objectid,geometry,index_right,service_name
0,1,2024-06-06 00:00:00+00:00,H,"65'5"" W OF 18TH ST",54421066,R50,ROW B/GAR 3 STY MASONRY,1,SINGLE FAMILY,373,...,Y,19145,RSA5,1001474749,21,ROW OLD STYLE,625493651,POINT (-8368801.614 4853114.259),NaN,NaN
1,2,2024-06-06 00:00:00+00:00,A,117' W OF 18TH ST,54421184,O50,ROW 3 STY MASONRY,1,SINGLE FAMILY,140,...,Y,19121,RSA5,1001520353,22,ROW TYPICAL,625493652,POINT (-8367444.407 4862158.067),NaN,NaN
2,3,2024-06-06 00:00:00+00:00,D,"135'11 1/2""N MIFFLIN",54421270,O10,ROW 1 STY MASONRY,1,SINGLE FAMILY,36,...,Y,19145,RM1,1001646206,23,ROW POST WAR,625493653,POINT (-8370301.088 4855801.554),NaN,NaN
3,4,2024-06-06 00:00:00+00:00,D,"26'5 1/2""N MIFFLIN ST",54421269,O10,ROW 1 STY MASONRY,1,SINGLE FAMILY,36,...,Y,19145,RM1,1001646217,23,ROW POST WAR,625493654,POINT (-8370308.435 4855758.874),NaN,NaN
4,5,2024-06-06 00:00:00+00:00,None,"297'8"" W 17TH ST",54421205,CA0,APTS 5-50 UNITS MASONRY,14,APARTMENTS > 4 UNITS,140,...,None,19130,RM4,1001242337,806,APARTMENTS - BLT AS RESID,625493655,POINT (-8367386.855 4861872.922),752984.0,Information Request
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582773,1416,2024-06-06 00:00:00+00:00,None,407' W 50TH ST,54413155,H30,SEMI/DET 2 STY MASONRY,1,SINGLE FAMILY,85,...,Y,19139,RSA5,1001140443,32,TWIN CONVENTIONAL,625494965,POINT (-8373760.007 4859901.535),NaN,NaN
582774,1417,2024-06-06 00:00:00+00:00,None,210' W 50TH ST,54413156,O30,ROW 2 STY MASONRY,1,SINGLE FAMILY,73,...,None,19143,RM1,1001217562,24,ROW PORCH FRONT,625494966,POINT (-8373689.542 4858083.727),NaN,NaN
582775,1418,2024-06-06 00:00:00+00:00,F,"136'6"" N. ANNSBURY ST",54413336,R30,ROW B/GAR 2 STY MASONRY,1,SINGLE FAMILY,289,...,Y,19120,RM1,1001232070,24,ROW PORCH FRONT,625494967,POINT (-8361284.654 4868502.519),NaN,NaN
582776,1419,2024-06-06 00:00:00+00:00,F,278' W 46 ST,54413480,K50,S/D W/B GAR 3 STY MASONRY,1,SINGLE FAMILY,79,...,None,19143,RSA3,1001313055,36,TWIN OLD STYLE,625494968,POINT (-8372982.218 4858811.943),NaN,NaN
582777,1420,2024-06-06 00:00:00+00:00,D,"159'7 1/8"" NE BUCKIUS",54413128,O30,ROW 2 STY MASONRY,1,SINGLE FAMILY,184,...,Y,19137,RSA5,1001199186,22,ROW TYPICAL,625494969,POINT (-8356616.472 4865974.685),NaN,NaN

In [13]:
# 3. Feature engineering: count complaints per parcel
feat = (joined.groupby("parcel_number").service_name.count().rename("complaint_ct").reset_index())

df = props.merge(feat, on="parcel_number", how="left")

df["complaint_ct"] = df["complaint_ct"].fillna(0).astype(int)

df

,cartodb_id,assessment_date,basements,beginning_point,book_and_page,building_code,building_code_description,category_code,category_code_description,census_tract,...,year_built,year_built_estimate,zip_code,zoning,pin,building_code_new,building_code_description_new,objectid,geometry,complaint_ct
0,1,2024-06-06 00:00:00+00:00,H,"65'5"" W OF 18TH ST",54421066,R50,ROW B/GAR 3 STY MASONRY,1,SINGLE FAMILY,373,...,1960,Y,19145,RSA5,1001474749,21,ROW OLD STYLE,625493651,POINT (-8368801.614 4853114.259),0
1,2,2024-06-06 00:00:00+00:00,A,117' W OF 18TH ST,54421184,O50,ROW 3 STY MASONRY,1,SINGLE FAMILY,140,...,1915,Y,19121,RSA5,1001520353,22,ROW TYPICAL,625493652,POINT (-8367444.407 4862158.067),0
2,3,2024-06-06 00:00:00+00:00,D,"135'11 1/2""N MIFFLIN",54421270,O10,ROW 1 STY MASONRY,1,SINGLE FAMILY,36,...,1950,Y,19145,RM1,1001646206,23,ROW POST WAR,625493653,POINT (-8370301.088 4855801.554),0
3,4,2024-06-06 00:00:00+00:00,D,"26'5 1/2""N MIFFLIN ST",54421269,O10,ROW 1 STY MASONRY,1,SINGLE FAMILY,36,...,1950,Y,19145,RM1,1001646217,23,ROW POST WAR,625493654,POINT (-8370308.435 4855758.874),0
4,5,2024-06-06 00:00:00+00:00,None,"297'8"" W 17TH ST",54421205,CA0,APTS 5-50 UNITS MASONRY,14,APARTMENTS > 4 UNITS,140,...,1915,None,19130,RM4,1001242337,806,APARTMENTS - BLT AS RESID,625493655,POINT (-8367386.855 4861872.922),1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582773,1416,2024-06-06 00:00:00+00:00,None,407' W 50TH ST,54413155,H30,SEMI/DET 2 STY MASONRY,1,SINGLE FAMILY,85,...,1925,Y,19139,RSA5,1001140443,32,TWIN CONVENTIONAL,625494965,POINT (-8373760.007 4859901.535),0
582774,1417,2024-06-06 00:00:00+00:00,None,210' W 50TH ST,54413156,O30,ROW 2 STY MASONRY,1,SINGLE FAMILY,73,...,1925,None,19143,RM1,1001217562,24,ROW PORCH FRONT,625494966,POINT (-8373689.542 4858083.727),0
582775,1418,2024-06-06 00:00:00+00:00,F,"136'6"" N. ANNSBURY ST",54413336,R30,ROW B/GAR 2 STY MASONRY,1,SINGLE FAMILY,289,...,1930,Y,19120,RM1,1001232070,24,ROW PORCH FRONT,625494967,POINT (-8361284.654 4868502.519),0
582776,1419,2024-06-06 00:00:00+00:00,F,278' W 46 ST,54413480,K50,S/D W/B GAR 3 STY MASONRY,1,SINGLE FAMILY,79,...,1925,None,19143,RSA3,1001313055,36,TWIN OLD STYLE,625494968,POINT (-8372982.218 4858811.943),0
582777,1420,2024-06-06 00:00:00+00:00,D,"159'7 1/8"" NE BUCKIUS",54413128,O30,ROW 2 STY MASONRY,1,SINGLE FAMILY,184,...,1925,Y,19137,RSA5,1001199186,22,ROW TYPICAL,625494969,POINT (-8356616.472 4865974.685),0

In [14]:
df[df['complaint_ct'] > 0]

,cartodb_id,assessment_date,basements,beginning_point,book_and_page,building_code,building_code_description,category_code,category_code_description,census_tract,...,year_built,year_built_estimate,zip_code,zoning,pin,building_code_new,building_code_description_new,objectid,geometry,complaint_ct
4,5,2024-06-06 00:00:00+00:00,None,"297'8"" W 17TH ST",54421205,CA0,APTS 5-50 UNITS MASONRY,14,APARTMENTS > 4 UNITS,140,...,1915,None,19130,RM4,1001242337,806,APARTMENTS - BLT AS RESID,625493655,POINT (-8367386.855 4861872.922),1
6,7,2024-06-06 00:00:00+00:00,None,SWC 17TH ST,54421209,S30,ROW W/OFF STR 2 STY MASON,3,MIXED USE,30,...,1925,None,19146,CMX1,1001179408,821,ROW MIXED-COM/RES-BLT AS COM,625493657,POINT (-8368229.655 4856093.348),8
11,12,2024-06-06 00:00:00+00:00,None,SWC JUNIPER ST,54421040,590,RES CONDO 5+ STY MASONRY,1,SINGLE FAMILY,9,...,1900,Y,19107,CMX5,1001332191,08,CONDO FLATS,625493662,POINT (-8367182.361 4858359.179),4
27,28,2024-06-06 00:00:00+00:00,C,SWC OF FERNON ST,54420739,U50,ROW CONV/APT 3 STY MASON,2,MULTI FAMILY,28,...,2011,None,19148,RSA5,1001600416,25,ROW MODERN,625493678,POINT (-8366281.675 4855527.043),1
50,51,2024-06-06 00:00:00+00:00,None,878.694' NW STONEY LN,54421271,531,RES CONDO 2 STY MAS+OTH,1,SINGLE FAMILY,345,...,1980,Y,19115,RTA1,1001387466,27,TWIN POST WAR,625493631,POINT (-8353751.553 4878410.489),1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582641,582560,2024-06-06 00:00:00+00:00,None,135' N DREXEL RD,0000000,CA0,APTS 5-50 UNITS MASONRY,14,APARTMENTS > 4 UNITS,117,...,1927,None,19131,RSA3,1001664663,828,APTS - GARDEN,626075776,POINT (-8375759.751 4864656.305),1
582655,582541,2024-06-06 00:00:00+00:00,D,60' NE WILMOT ST,0000000,H30,SEMI/DET 2 STY MASONRY,1,SINGLE FAMILY,183,...,1920,None,19137,RSA5,1001062569,32,TWIN CONVENTIONAL,626076264,POINT (-8357220.936 4866114.773),6
582682,582586,2024-06-06 00:00:00+00:00,None,120' S PINE ST,0000000,CA0,APTS 5-50 UNITS MASONRY,14,APARTMENTS > 4 UNITS,11,...,1900,None,19147,RM1,1001608402,804,APARTMENTS - LOW RISE,626076278,POINT (-8366458.228 4857828.319),1
582703,582625,2024-06-06 00:00:00+00:00,1,"113'2"" NW EMERY S\",None,P76,ROW W/GAR 4 STY FRAME,1,SINGLE FAMILY,143,...,2021,None,19125,RSA5,1001680894,25,ROW MODERN,626076284,POINT (-8363382.582 4861407.092),1
582712,582634,2024-06-06 00:00:00+00:00,None,NEC 40TH ST,None,IA0,REST'RNT FASTFOOD MASONRY,4,COMMERCIAL,88,...,2024,None,19104,CMX4,1001685476,245,RETAIL CONDO,626076293,POINT (-8371485.527 4859318.604),1

In [15]:
df["shape_area"] = props.geometry.area

In [16]:
df_cleaned = df.drop(index=df[df["sale_price"].isnull()].index)

In [ ]:
import xgboost as xgb

# 4. Simple model: predict log(sale_price) from complaint_ct & area
X = df_cleaned[["complaint_ct", "shape_area"]]

y = np.log1p(df_cleaned["sale_price"])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

# m = RandomForestRegressor(n_estimators=200).fit(X_train, y_train)

# print("Test R²:", m.score(X_test, y_test))

model = xgb.XGBRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.7,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train,
          eval_set=[(X_train, y_train),(X_test, y_test)],
          early_stopping_rounds=50,
          verbose=False)

print("XGB R²:", model.score(X_test, y_test))

XGBoostError:
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/Users/ColeHoffman/dev/gis_phl/gis-phl/venv/lib/python3.11/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <948FC7F9-7446-3923-BB9F-85890E78C765> /Users/ColeHoffman/dev/gis_phl/gis-phl/venv/lib/python3.11/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/Users/ColeHoffman/.pyenv/versions/3.11.4/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/ColeHoffman/.pyenv/versions/3.11.4/lib/libomp.dylib' (no such file), '/opt/homebrew/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libomp.dylib' (no such file), '/Users/ColeHoffman/.pyenv/versions/3.11.4/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/ColeHoffman/.pyenv/versions/3.11.4/lib/libomp.dylib' (no such file), '/opt/homebrew/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libomp.dylib' (no such file)"]

In [ ]:
# 5. Visualise predictions on an interactive map

df_cleaned["pred_price"] = np.expm1(m.predict(X))

# reproject for mapping
gd = df_cleaned.to_crs(4326)

# pull out only the fields Folium needs:
geojson = {
    "type": "FeatureCollection",
    "features": []
}
for _, row in gd.iterrows():
    geom = row.geometry
    if geom is None:
        continue   # skip parcels with no geometry
    geojson["features"].append({
        "type": "Feature",
        "geometry": geom.__geo_interface__,
        "properties": {
            "parcel_number": row.parcel_number,
            "pred_price": row.pred_price
        }
    })

In [63]:
import json
with open("data/philly_parcels.geojson", "w") as f:
    json.dump(geojson, f)

In [64]:
df_cleaned.to_csv("data/philly_parcels.csv", index=False)

In [ ]:
# Basic but does not scale well 
mmap = folium.Map(location=[39.95,-75.17], zoom_start=11, tiles="cartodbpositron")

folium.Choropleth(geo_data=geojson,
                  data=df_cleaned,
                  columns=["parcel_number","pred_price"],
                  key_on="feature.properties.parcel_number",
                  fill_color="YlGnBu",
                  legend_name="Predicted Sale Price").add_to(mmap)

mmap.save("philly_parcels.html")

# Scaled Solution

In [ ]:
%%bash
tippecanoe --force -o parcels.mbtiles -Z 10 -z 16 --drop-densest-as-needed data/philly_parcels.geojson

# install a lightweight MBTiles tile server
npm install -g tileserver-gl-light

# point it at your tileset
tileserver-gl-light parcels.mbtiles

In [65]:
# from IPython.display import IFrame
# IFrame("philly_parcels.html", width=800, height=600)

In [ ]:
%%bash
python -m http.server 8000